### ISSUE TITLE
Replace `github.com/go-resty/resty/v2` with `net/http`

### ISSUE THREAD

**Issue by ckaznocha** [Flagsmith/flagsmith-go-client#105]
All versions of the `resty` package are affected by [GO-2023-2328](https://pkg.go.dev/vuln/GO-2023-2328) with no available fix.

I'm not familiar with the `resty` package but I'm sure it could be swapped out for `net/http`. I'm happy to submit a PR to make the change.

**Comment by dabeeeenster** [comment]
Thanks for the heads up - a PR would be great!
