### ISSUE TITLE
Is the forced emptying of the analytics data map intentional?

### ISSUE THREAD

**Issue by JonasAlfredsson** [Flagsmith/flagsmith-go-client#74]
In the analytics Flush function the data map is [always emptied](https://github.com/Flagsmith/flagsmith-go-client/blob/main/analytics.go#L69), even in case of failure to transmit data to the server. Is this the intended behavior or should there be some `return` statements after the log messages?

**Comment by gagantrivedi** [comment]
On one hand, it is highly unlikely that this can make the program run out of memory, on the other hand this approach is slightly cleaner IMO @matthewelwell what do you think?

**Comment by JonasAlfredsson** [comment]
Created a pull request to better show what I mean.

**Comment by matthewelwell** [comment]
I tend to agree here with @JonasAlfredsson. We should not clear the map in case of a failure to communicate with the server. Interestingly, in the python client (which is the reference point for most implementations), we aren't explicitly handling this case either. I would suggest that we should in fact implement this across all of our SDKs. Do you agree @gagantrivedi ?

**Comment by gagantrivedi** [comment]
Yeah, I'd agree

**Comment by gagantrivedi** [comment]
fixed here: https://github.com/Flagsmith/flagsmith-go-client/pull/76
